### createDraw
POST http://localhost:8080/admin/draws
Content-Type: application/json

{
  "title": "Spring Draw",
  "endDate": "2026-04-25T18:00:00+03:00",
  "totalTickets": 100
}

### getAllDraws
GET http://localhost:8080/api/v1/draws

### getActiveDraws
GET http://localhost:8080/api/v1/draws?status=ACTIVE

### getCompletedDraws
GET http://localhost:8080/api/v1/draws?status=COMPLETED

### getDrawById
GET http://localhost:8080/api/v1/draws/1

### runDrawById
POST http://localhost:8080/admin/draws/1/run-draw

### getDrawResultById
GET http://localhost:8080/api/v1/draws/1/result