@host = http://localhost:8080

###------------ MAIN SCENARIO------------ ###


###------------ HEALTH------------ ###

# @name health
GET http://localhost:8080/health

###

# @name healthDb
GET http://localhost:8080/health/db

###--------------------------------------- ###

### ---------------------------------------
### REGISTER ADMIN
### do not forget to remove default admin from the database
### ---------------------------------------

###
# @name registerAdmin
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "login": "admin",
  "password": "admin123"
}

### ---------------------------------------
### REGISTER USER 1
### ---------------------------------------

# @name registerUser1
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "ivan",
  "password": "87654321"
}

### ---------------------------------------
### REGISTER USER 2
### ---------------------------------------

# @name registerUser2
POST {{host}}/auth/register
Content-Type: application/json

{
  "login": "marck",
  "password": "5432555789"
}


### ---------------------------------------
### ADMIN LOGIN
### do not forget to assign ADMIN role to the admin user in database
### ---------------------------------------

# @name loginAdmin
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin123"
}

> {%
    client.global.set("adminToken", response.body.token);
    client.log("adminToken = " + client.global.get("adminToken"));
%}

### ---------------------------------------
### LOGIN USER 1
### ---------------------------------------

# @name loginUser1
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "ivan",
  "password": "87654321"
}

> {%
    client.global.set("user1Token", response.body.token);
    client.log("user1Token = " + client.global.get("user1Token"));
%}


### ---------------------------------------
### LOGIN USER 2
### ---------------------------------------

# @name loginUser2
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "marck",
  "password": "5432555789"
}

> {%
    client.global.set("user2Token", response.body.token);
    client.log("user2Token = " + client.global.get("user2Token"));
%}


### ---------------------------------------
### CREATE DRAW
### ---------------------------------------

# @name createDraw
POST {{host}}/admin/draws
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "Draw HTTP Auto Test",
  "endDate": "2026-12-31T18:00:00+03:00",
  "totalTickets": 5
}

> {%
    client.global.set("drawId", response.body.id);
    client.log("drawId = " + client.global.get("drawId"));
%}

### ---------------------------------------

# @name createDraw2
POST {{host}}/admin/draws
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "Draw HTTP Auto Test 2",
  "endDate": "2026-12-31T18:00:00+03:00",
  "totalTickets": 5
}

> {%
    client.global.set("draw2Id", response.body.id);
    client.log("draw2Id = " + client.global.get("draw2Id"));
%}


### ---------------------------------------
### BUY TICKETS
### ---------------------------------------

# @name buyTicketUser1
POST {{host}}/draws/{{drawId}}/tickets
Authorization: Bearer {{user1Token}}

### ---------------------------------------

# @name buyTicketUser2
POST {{host}}/draws/{{draw2Id}}/tickets
Authorization: Bearer {{user1Token}}

### ---------------------------------------

# @name buyTicketAdmin
POST {{host}}/draws/{{draw2Id}}/tickets
Authorization: Bearer {{adminToken}}


###---------------------------------------
### MY TICKETS / RESULTS
###---------------------------------------

# @name myTickets
GET {{host}}/me/tickets
Authorization: Bearer {{user1Token}}

###

# @name myTickets
GET {{host}}/me/results
Authorization: Bearer {{user2Token}}

###
# @name adminTickets
GET {{host}}/me/results
Authorization: Bearer {{adminToken}}


### ---------------------------------------
### MANUAL STEP
### ---------------------------------------
### Before the next request, move draw {{drawId}} to CLOSED
### through DB or wait for scheduler.

### ---------------------------------------
### RUN DRAW
### ---------------------------------------

# @name runDraw
POST {{host}}/admin/draws/{{drawId}}/run-draw
Authorization: Bearer {{adminToken}}

### ---------------------------------------

# @name runDraw2
POST {{host}}/admin/draws/{{draw2Id}}/run-draw
Authorization: Bearer {{adminToken}}

### ---------------------------------------
### CHECK RESULTS
### ---------------------------------------

# @name getAllDraws
GET {{host}}/draws

### ---------------------------------------

# @name getDrawById
GET {{host}}/draws/{{draw2Id}}

### ---------------------------------------

# @name getDrawResult
GET {{host}}/draws/{{drawId}}/result

###
# @name getDraw2Result
GET {{host}}/draws/{{draw2Id}}/result

###
# @name myResultsAfterDraw
GET {{host}}/me/results
Authorization: Bearer {{user1Token}}

###---------------------------------------
### DRAWS LIST
###---------------------------------------

# @name activeDraws
GET {{host}}/draws?status=ACTIVE

###
# @name closedDraws
GET {{host}}/draws?status=CLOSED

###
# @name completedDraws
GET {{host}}/draws?status=COMPLETED


###---------------------------------------
### FAILURES
###---------------------------------------

###------------ REGISTER FAILURES------------ ###
###

# @name registerEmptyLogin
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "login": "",
  "password": "123456"
}

###
# @name registerEmptyPassword
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "login": "ivan2",
  "password": ""
}

###
# @name registerBadPassword
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "login": "ivan3",
  "password": "1234"
}

###
# @name registerDuplicateIvan
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "login": "ivan",
  "password": "12345678"
}

###
# @name registerShortLogin
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "login": "ab",
  "password": "12345678"
}

###
# @name registerLoginWithSpace
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "login": "ivan petrov",
  "password": "12345678"
}

###
# @name registerLoginBadChars
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "login": "ivan@petrov",
  "password": "12345678"
}

###
# @name registerNullLogin
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "login": null,
  "password": "12345678"
}

###
# @name registerNullPassword
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "login": "user123",
  "password": null
}


###---------------------------------------
###---------------------------------------
### !!!!!!! ADDITIONAL CHECKS !!!!!!!!!
###---------------------------------------
###---------------------------------------

###---------------------------------------
### MY MAIN API CHECKS
###---------------------------------------

### ---------------------------------------
### USERS / ADMIN BASIC CHECKS
### ---------------------------------------

# @name meUser1Check
GET {{host}}/users/me
Authorization: Bearer {{user1Token}}

> {%
    client.test("meUser1Check status is 200", function() {
        client.assert(response.status === 200, "Expected 200");
    });
    client.test("meUser1Check login is ivan", function() {
        client.assert(response.body.login === "ivan", "Expected login ivan");
    });
%}

###
# @name adminPingCheck
GET {{host}}/admin/ping
Authorization: Bearer {{adminToken}}

> {%
    client.test("adminPingCheck status is 200", function() {
        client.assert(response.status === 200, "Expected 200");
    });
    client.test("adminPingCheck role is ADMIN", function() {
        client.assert(response.body.role === "ADMIN", "Expected ADMIN role");
    });
%}

###
# @name usersListCheck
GET {{host}}/users
Authorization: Bearer {{adminToken}}

> {%
    client.test("usersListCheck status is 200", function() {
        client.assert(response.status === 200, "Expected 200");
    });
    client.test("usersListCheck returns array", function() {
        client.assert(Array.isArray(response.body), "Expected array");
    });
%}

###
# @name loggedInUsersCheck
GET {{host}}/admin/logged-in-users
Authorization: Bearer {{adminToken}}

> {%
    client.test("loggedInUsersCheck status is 200", function() {
        client.assert(response.status === 200, "Expected 200");
    });
    client.test("loggedInUsersCheck returns array", function() {
        client.assert(Array.isArray(response.body), "Expected array");
    });
%}

### ---------------------------------------
### DRAWS / TICKETS BASIC CHECKS
### ---------------------------------------

# @name drawByIdCheck
GET {{host}}/draws/{{drawId}}

> {%
    client.test("drawByIdCheck status is 200", function() {
        client.assert(response.status === 200, "Expected 200");
    });
    client.test("drawByIdCheck id is correct", function() {
        client.assert(String(response.body.id) === String(client.global.get("drawId")), "Unexpected draw id");
    });
%}

### @name draw2ByIdCheck
GET {{host}}/draws/{{draw2Id}}

> {%
    client.test("drawByIdCheck status is 200", function() {
        client.assert(response.status === 200, "Expected 200");
    });
    client.test("drawByIdCheck id is correct", function() {
        client.assert(String(response.body.id) === String(client.global.get("draw2Id")), "Unexpected draw id");
    });
%}

###
# @name myTicketsCheckUser1
GET {{host}}/me/tickets
Authorization: Bearer {{user1Token}}

> {%
    client.test("myTicketsCheckUser1 status is 200", function() {
        client.assert(response.status === 200, "Expected 200");
    });
    client.test("myTicketsCheckUser1 returns array", function() {
        client.assert(Array.isArray(response.body), "Expected array");
    });
%}

###
# @name myResultsCheckUser1
GET {{host}}/me/results
Authorization: Bearer {{user1Token}}

> {%
    client.test("myResultsCheckUser1 status is 200", function() {
        client.assert(response.status === 200, "Expected 200");
    });
    client.test("myResultsCheckUser1 returns array", function() {
        client.assert(Array.isArray(response.body), "Expected array");
    });
%}

###---------------------------------------
### MISSED MAIN SCENARIOS
###---------------------------------------

### ---------------------------------------
### REPEATED LOGIN RETURNS THE SAME TOKEN
### ---------------------------------------

# @name loginUser1Again
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "ivan",
  "password": "87654321"
}

> {%
    client.test("loginUser1Again status is 200", function() {
        client.assert(response.status === 200, "Expected 200");
    });
    client.test("loginUser1Again returns the same token", function() {
        client.assert(response.body.token === client.global.get("user1Token"), "Expected the same token");
    });
%}

### ---------------------------------------
### LOGOUT / LOGIN AGAIN
### ---------------------------------------

# @name logoutUser2
POST {{host}}/auth/logout
Authorization: Bearer {{user2Token}}

> {%
    client.test("logoutUser2 status is 200", function() {
        client.assert(response.status === 200, "Expected 200");
    });
%}

###
# @name loginUser2AfterLogout
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "marck",
  "password": "5432555789"
}

> {%
    client.global.set("user2Token", response.body.token);
    client.log("user2Token = " + client.global.get("user2Token"));
%}

### ---------------------------------------
### DRAW WITHOUT RESULT YET + SOLD OUT DRAW
### ---------------------------------------

# @name createExtraDraw
POST {{host}}/admin/draws
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "Draw HTTP Extra Test",
  "endDate": "2026-12-31T18:00:00+03:00",
  "totalTickets": 2
}

> {%
    client.global.set("extraDrawId", response.body.id);
    client.log("extraDrawId = " + client.global.get("extraDrawId"));
%}

###
# @name getExtraDrawResultBeforeRun
GET {{host}}/draws/{{extraDrawId}}/result

###
# @name buyExtraDrawTicketUser1
POST {{host}}/draws/{{extraDrawId}}/tickets
Authorization: Bearer {{user1Token}}

###
# @name buyExtraDrawTicketUser2
POST {{host}}/draws/{{extraDrawId}}/tickets
Authorization: Bearer {{user2Token}}

###---------------------------------------
### EXTRA FAILURES / ERROR CHECKS
###---------------------------------------

###------------ LOGIN FAILURES------------ ###

###
# @name loginWrongPassword
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "ivan",
  "password": "wrongpass123"
}

###
# @name loginUnknownUser
POST {{host}}/auth/login
Content-Type: application/json

{
  "login": "unknown_user",
  "password": "12345678"
}

###------------ AUTH FAILURES------------ ###

###
# @name meWithoutToken
GET {{host}}/users/me

###
# @name meWithBadToken
GET {{host}}/users/me
Authorization: Bearer bad-token

###
# @name logoutWithBadToken
POST {{host}}/auth/logout
Authorization: Bearer bad-token

###------------ ADMIN FAILURES------------ ###

###
# @name createDrawWithoutToken
POST {{host}}/admin/draws
Content-Type: application/json

{
  "title": "Draw Without Token",
  "endDate": "2026-12-31T18:00:00+03:00",
  "totalTickets": 3
}

###
# @name createDrawByUserForbidden
POST {{host}}/admin/draws
Content-Type: application/json
Authorization: Bearer {{user1Token}}

{
  "title": "Draw Forbidden",
  "endDate": "2026-12-31T18:00:00+03:00",
  "totalTickets": 3
}

###
# @name usersListByUserForbidden
GET {{host}}/users
Authorization: Bearer {{user1Token}}

###
# @name adminPingByUserForbidden
GET {{host}}/admin/ping
Authorization: Bearer {{user1Token}}

###
# @name loggedInUsersByUserForbidden
GET {{host}}/admin/logged-in-users
Authorization: Bearer {{user1Token}}

###
# @name runDrawByUserForbidden
POST {{host}}/admin/draws/{{drawId}}/run-draw
Authorization: Bearer {{user1Token}}

###------------ DRAW FAILURES------------ ###

###
# @name createDrawEmptyTitle
POST {{host}}/admin/draws
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "",
  "endDate": "2026-12-31T18:00:00+03:00",
  "totalTickets": 3
}

###
# @name createDrawZeroTickets
POST {{host}}/admin/draws
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "Draw Zero Tickets",
  "endDate": "2026-12-31T18:00:00+03:00",
  "totalTickets": 0
}

###
# @name createDrawNullEndDate
POST {{host}}/admin/draws
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "Draw Null End Date",
  "endDate": null,
  "totalTickets": 3
}

###
# @name getMissingDraw
GET {{host}}/draws/999999

###
# @name getMissingDrawResult
GET {{host}}/draws/999999/result

###
# @name getDrawsBadStatus
GET {{host}}/draws?status=BAD_STATUS

###------------ TICKET FAILURES------------ ###

###
# @name buyTicketWithoutToken
POST {{host}}/draws/{{drawId}}/tickets

###
# @name buyTicketMissingDraw
POST {{host}}/draws/999999/tickets
Authorization: Bearer {{user1Token}}

###
# @name buyTicketSoldOut
POST {{host}}/draws/{{extraDrawId}}/tickets
Authorization: Bearer {{adminToken}}

###------------ RUN DRAW FAILURES------------ ###

###
# @name runActiveDrawShouldFail
POST {{host}}/admin/draws/{{extraDrawId}}/run-draw
Authorization: Bearer {{adminToken}}

###
# @name runCompletedDrawAgainShouldFail
POST {{host}}/admin/draws/{{drawId}}/run-draw
Authorization: Bearer {{adminToken}}
